Admin panel testing
Sukellusilmoitus/frontend pull request #73
Opened 2022-03-30 08:06 UTC by Shmuli02

Admin panelin e2e testaus.

2022-04-07 10:23 UTC, Shmuli02 commented
divadate lisääminen näyttää vaikuttavan suekklusilmoitusten näyttämiseen. Kun PR #85 saadaan mergettyä niin ongelma täytyy korjata

2022-04-07 11:05 UTC, Skorp7 commented
Pitää kattoa kunnolla sitten kun diveDate on mergetty mutta nopeesti katottuna:

Hyväksyttävissä hylyissä on näkyvissä toi is_ancient parametri mut hylyissä ei.  Periaatteessa sitä ei varmaan oo tarvetta päästä muuttamaan koska muinaisjäännökset tulee sen wfs-rajapinnan kautta sit kun ne on virallisesti todettu sellasiks. Eli ehkä sen vois ottaa pois näkyvistä myös hyväksyttävissä hylyissä tai sit laittaa siihen suomennoksen "muinaisjäännös".

Ja hyväksyttävissä hylyissä toi is_pending on musta vähän hämäävä, kun se nappula on tavallaan "päällä" jo ja siinä on `tarkistettu` tekstinä, vaikka se nimen omaan ei oo vielä tarkistettu. Musta siihen olis parempi joku "odottaa tarkistusta" niin sit on loogista että se on päällä. Tai sit kääntää nappulan niin että se ei oo päällä aluksi.

lmotusten selaus sivulta toiselle toimii nyt hyvin.

Admin-paneelista ei vielä pääse pois. Saiskohan sen toiminnon yhdistettyä tohon sammutusnappiin yläkulmassa. Siitä voi tehdä uuden taskinkin.

2022-04-08 09:03 UTC, Skorp7 commented
DiveDate-PR:n hyväksymisen jälkeen löytyi vaan yksi bugi lisää. Sukellusilmotuksissa hylyn klikkaaminen ei johtanut mihinkään. Tein siitä korjausehdotuksen koodiin.
Testit menee läpi paitsi setUp bugasi mulla joka ajossa jossa lisätään hylkyjä ja sukelluksia. Lisäks jotkut testit hajoili kun odotusaikaa ei joka ajolla ollut tarpeeksi. Voi olla että tulee CI:ssä ongelmia kun se on yleensä ollut vielä hitaampi.

Muuten sukellusilmotukset-sivu on nyt paljon entistä parempi, kun on linkit ja sukeltajan nimi esillä jne. 

Voi mun puolesta mergee kun eka korjaa ton "tarkistettu" sanamuodon, tarkistaa testien setUp-ajon ja korjaa sukellusilmotuksen target-linkin.

2022-04-08 09:04 UTC, Skorp7 approved these changes

2022-04-20 15:00 UTC, jpasikainen requested changes

2022-04-27 11:15 UTC, Skorp7 approved these changes
Yksikkötestit menee läpi,cypress-testeistä kaikki menee läpi paitsi mulla ei mennyt admin-panelin testi läpi jossa yritetään klikata sukellusilmoituksen edit-nappulaa. Nappula jää piiloon joten se ei löydy. Ongelmaa ei välttämättä oo CI:ssä..

Ilmoitusten tekeminen, rekisteröinti, kirjautuminen toimii. Admin-panelissa tietojen muokkaus toimii. 

Hylyn omalla sivulla jostain syystä pitkä sukellusilmoituslista ei kääriydy enää "näytä enemmän" nappulan taakse vaikka omalla sivulla toimii. En löytänyt tästä PR:stä koodia joka aiheuttaisi ton, joten sitä voi tutkia myöhemmin.

Merge-konfliktit kun on katsottu niin musta tän voi mergetä tälläsenä. Korjaa ton yhen cypress-testin jos se ei mee läpi CI:ssä. Tärkee PR joka olis hyvä saada jo tuotantoon.

2022-04-27 12:24 UTC, merged