autoFillTests
Sukellusilmoitus/frontend pull request #98
Opened 2022-04-21 13:05 UTC by synesteesia

jest testit lomakkeiden automaattiselle täytölle

2022-04-21 14:39 UTC, synesteesia commented
pyörittelin cypress testejä aikani mutta sain toimimaan vain antipatternilla...

2022-04-22 06:50 UTC, Skorp7 requested changes
Jest-testit näyttää toimivan hyvin.
e2e-testin ostalta kokeilin samaan tyyliin kuin J-P oli tehnyt omat testit. Tää näytti toimivan tässäkin. Olettaa toki että ton niminen testikäyttäjä on tietokannassa. Laitoin ehdotukset kommentteina, jos vielä testaat että toimii sullakin.

2022-04-22 06:50 UTC, Skorp7 commented on cypress/integration/dive_notification_page_spec.js
> +
``` suggestion
const REACT_APP_SERVER_URL = 'https://sukellusilmo-back-test.herokuapp.com/';
```

2022-04-22 06:50 UTC, Skorp7 commented on cypress/integration/dive_notification_page_spec.js
>  })
``` suggestion
})

let auth;

before(function fetchUser () {
  cy.request('POST', `${REACT_APP_SERVER_URL}/api/login`, {
    username: 'usernametest',
    password: 'passwordtest',
  })
  .its('body')
  .then((res) => {
    auth = res.auth;
  });
});
```

2022-04-22 06:50 UTC, Skorp7 commented on cypress/integration/dive_notification_page_spec.js
> +    cy.wait(3000);
``` suggestion
    cy.visit('/hylyt', {
      onBeforeLoad (win) {
        win.localStorage.setItem('auth', auth);
      },
    });
```

2022-04-22 06:50 UTC, Skorp7 commented on cypress/integration/dive_notification_page_spec.js
> +    cy.visit('/hylyt');
```suggestion
```

2022-04-22 08:02 UTC, synesteesia commented
joo tällä tyylillä kokeilin kans aikasemmin mut jostain syystä ei toiminu, nyt näyttäis kuitenkin

2022-04-22 08:02 UTC, merged